language: rust
matrix:
  include:
    - rust: stable
      env: RUST_CHANNEL=stable
    - rust: beta
      env: RUST_CHANNEL=beta
    - rust: nightly
      env: RUST_CHANNEL=nightly
install:
  - cargo install cargo-bloat
  - if [ $RUST_CHANNEL == "nightly" ]; then
      cargo install clippy;
      cargo install cargo-expand;
    fi
script:
  - cargo build --verbose
  - cargo test --verbose
  - ./check-test-mls.sh
  - cargo bloat --release -n 20
  - cargo bloat --release --crates
  - if [ $RUST_CHANNEL == "nightly" ]; then
      cargo clippy;
      cargo expand --lib;
    fi
